### ISSUE TITLE
Icons no longer visible after updating to HACS 2.0+

### ISSUE THREAD

**Issue by curtash** [wowgamr/animated-weather-card#13]
I've updated to HACS 2.0.1 and most of the icons do not display. I've tried deleting browser cache and tried Chrome & Safari without success.

The image below shows the Animated Weather Card top and default below.

![Screenshot 2024-09-10 at 08 58 09](https://github.com/user-attachments/assets/9fe7f4f2-f257-4334-8b48-a016b95e4677)

**Comment by ksiwy87** [comment]
Same here. Icons are disappeared after HACS update.

**Comment by berkavil** [comment]
same here, not sure if its caused by the latest HACS version or core last update (a week ago), I installed both to the latest versions and I se no more icons on the wather card.
I guess it might be caused by different path rules in HA? (no more /hacsfiles/themes/... but /homeassistant/themes/... ) or something similar?
thx. for any clue
W.

**Comment by auggy** [comment]
> same here, not sure if its caused by the latest HACS version or core last update (a week ago), I installed both to the latest versions and I se no more icons on the wather card. I guess it might be caused by different path rules in HA? (no more /hacsfiles/themes/... but /homeassistant/themes/... ) or something similar? thx. for any clue W.

The paths definitely changed to /homeassistant/themes/… I tried changing them in the yaml and it didn’t work. I also tried with /local/themes/… because I saw another theme referencing that path and just /themes/… and nothing seems to work.

**Comment by dersch81** [comment]
same here

**Comment by fumsi** [comment]
1) copy the ./homeassistant/themes/animated-weather-card folder to ./homeassistant/www/community
2) edit yaml file in ./homeassistant/themes/animated-weather-card to look like this 

Animated Weather Card:
    weather-icon-clear-night: url("/hacsfiles/animated-weather-card/icons/clear-night.svg")
    weather-icon-cloudy: url("/hacsfiles/animated-weather-card/icons/cloudy.svg")
    weather-icon-fog: url("/hacsfiles/animated-weather-card/icons/fog.svg")
    weather-icon-lightning: url("/hacsfiles/animated-weather-card/icons/lightning.svg")
    weather-icon-lightning-rainy: url("/hacsfiles/animated-weather-card/icons/lightning.svg")
    weather-icon-partlycloudy: url("/hacsfiles/animated-weather-card/icons/partlycloudy.svg")
    weather-icon-pouring: url("/hacsfiles/animated-weather-card/icons/pouring.svg")
    weather-icon-rainy: url("/hacsfiles/animated-weather-card/icons/rainy.svg")
    weather-icon-hail: url("/hacsfiles/animated-weather-card/icons/hail.svg")
    weather-icon-snowy: url("/hacsfiles/animated-weather-card/icons/snowy.svg")
    weather-icon-snowy-rainy: url("/hacsfiles/animated-weather-card/icons/hail.svg")
    weather-icon-sunny: url("/hacsfiles/animated-weather-card/icons/sunny.svg")
    weather-icon-windy: url("/hacsfiles/animated-weather-card/icons/cloudy.svg")
    weather-icon-windy-variant: url("/hacsfiles/animated-weather-card/icons/partlycloudy.svg")
    weather-icon-exceptional: url("/hacsfiles/animated-weather-card/icons/exceptional.svg")

3) reload homeassistant

**Comment by auggy** [comment]
Thank you @fumsi that worked perfectly

**Comment by berkavil** [comment]
ok solved thank you

**Comment by hendrikderek** [comment]
Worked for me also. Thank you!
