### ISSUE TITLE
Possibility to use with non-default theme

### ISSUE THREAD

**Issue by anyuta1166** [wowgamr/animated-weather-card#2]
Hi,

Any chance to add a possibility to use this with a non-default theme?

I liked your animated weather card, but I use non-default black-green theme.

**Comment by wowgamr** [comment]
Привет!
Нужно загрузить иконки (папка **icons**) в папку **themes**. У вашей темы должен быть свой yaml-файл, в конец которого нужно добавить переопределения переменных (они начинаются с "_weather-icon-_") из [этого](https://github.com/wowgamr/animated-weather-card/blob/master/themes/animated-weather-card.yaml) файла.

**Comment by anyuta1166** [comment]
Спасибо за подсказку. Правда, думаю, что либо сломается обновление темы через HACS, либо после каждого обновления темы придется каждый раз заново делать все вышеперечисленное.
Нельзя это было реализовать как-то по-другому, плагином например? Я нуб в программировании, прошу сильно не бить за такой вопрос. Если нельзя - значит нельзя.

**Comment by wowgamr** [comment]
Увы, соединить всё в одну тему не получится. У них есть "главный" файл с переменными. В любом случае при каждом обновлении вашей темы придётся заново дополнять файл. Сами иконки никуда при этом не пропадут.
Но не думаю, что обновления для вашей темы часто выходят. Там особо нечего обновлять.

**Comment by anyuta1166** [comment]
Ясно, спасибо.
