### ISSUE TITLE
integration into transparentblue theme

### ISSUE THREAD

**Issue by gribouk** [wowgamr/animated-weather-card#3]
Hello, everyone!

I am having problems integrating animated weather card into transparentblue theme while following the directions at the end of your manual. I have tested many versions of what I should do and provide the last version of the syntax I stopped at.  I have created the 'icons' folder in the 'transparentblue' folder and have coppied all svg files there. This is what I've pasted at the end of the transparentblue.yaml:

Animated Weather Card:
    weather-icon-clear-night: url("/hacsfiles/themes/transparentblue/icons/clear-night.svg")
    weather-icon-cloudy: url("/hacsfiles/themes/transparentblue/icons/cloudy.svg")
    weather-icon-fog: url("/hacsfiles/themes/transparentblue/icons/fog.svg")
    weather-icon-lightning: url("/hacsfiles/themes/transparentblue/icons/lightning.svg")
    weather-icon-lightning-rainy: url("/hacsfiles/themes/transparentblue/icons/lightning.svg")
    weather-icon-partlycloudy: url("/hacsfiles/themes/transparentblue/icons/partlycloudy.svg")
    weather-icon-pouring: url("/hacsfiles/themes/transparentblue/icons/pouring.svg")
    weather-icon-rainy: url("/hacsfiles/themes/transparentblue/icons/rainy.svg")
    weather-icon-hail: url("/hacsfiles/themes/transparentblue/icons/hail.svg")
    weather-icon-snowy: url("/hacsfiles/themes/transparentblue/icons/snowy.svg")
    weather-icon-snowy-rainy: url("/hacsfiles/themes/transparentblue/icons/hail.svg")
    weather-icon-sunny: url("/hacsfiles/themes/transparentblue/icons/sunny.svg")
    weather-icon-windy: url("/hacsfiles/themes/transparentblue/icons/cloudy.svg")
    weather-icon-windy-variant: url("/hacsfiles/themes/transparentblue/icons/partlycloudy.svg")
    weather-icon-exceptional: url("/hacsfiles/themes/transparentblue/icons/exceptional.svg")

I also tried with 'animated-weathe-card' instead of 'transparentblue' in the path, but with no success. What is the proper way to have animated weather card in other theme?

**Comment by wowgamr** [comment]
Hello!
Can you please attach transparentblue.yaml ?
It looks like line `Animated Weather Card:` is unnecessary.

**Comment by gribouk** [comment]
[transparentblue.zip](https://github.com/wowgamr/animated-weather-card/files/5555249/transparentblue.zip)

**Comment by wowgamr** [comment]
Try to remove line 124 (`Animated Weather Card:`).

**Comment by gribouk** [comment]
This I have already tried. HA gives error for that:

Error loading /config/configuration.yaml: while parsing a block mapping
in "/config/themes/transparentblue/transparentblue.yaml", line 10, column 3
expected <block end>, but found '<block mapping start>'
in "/config/themes/transparentblue/transparentblue.yaml", line 125, column 5

**Comment by gribouk** [comment]
I belive I fixed it. There was extra space when the links were coppied. I have aligned whole blok as the rest of the entries above and the errore has gone. Now after reboot the icons are animated. Thanks!

**Comment by wowgamr** [comment]
Try this [transparentblue.zip](https://github.com/wowgamr/animated-weather-card/files/5555328/transparentblue.zip)

**Comment by wowgamr** [comment]
Yep, extra spaces.
