### ISSUE TITLE
I do not see the theme

### ISSUE THREAD

**Issue by vawaver** [wowgamr/animated-weather-card#4]
Home Assistant 2021.1.1
I had installed addon via HACS, restarted HA but I do not see Animated Weather Card in Themes.
What did I wrong?

**Comment by wowgamr** [comment]
Hi!
Just updated to 2021.1.1 and theme works fine. Make sure that you installed addon. After that you will see it in profile settings.
![image](https://user-images.githubusercontent.com/4518407/104119809-4c1fd180-5343-11eb-8a78-89c292ffdbe6.png)
