### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by rcanpolat** [wowgamr/animated-weather-card#5]
Unable to uninstall. I click uninstall and nothing happens. Tried rebooting, tried reinstalling and then re-uninstalling and nothing. 

UPDATE: I renamed the themes folder to "themes-delete", rebooted home assistant, then went into HACS and i could uninstall, then manually delete themes folder & remove code from config.yaml file

**Comment by wowgamr** [comment]
Hello!
Uninstallation is a HACS function. Looks like it is HACS bug (or folder permissions).
