### ISSUE TITLE
Forcasted precipitation amounts are in wrong units?

### ISSUE THREAD

**Issue by tescher** [wowgamr/animated-weather-card#7]
Forecasted precipitation amounts are obviously incorrect. Showing multiple inches for each day. Perhaps it is supposed to be in mm? Using Open Weather Map as the provider
![Capture](https://user-images.githubusercontent.com/2557404/140100373-a4be6858-d6a5-4b1a-a454-d0213481ed04.PNG)

**Comment by wowgamr** [comment]
Hello!
You need to contact developer of this weather integration. My plugin just replace images. Nothing more.

**Comment by tescher** [comment]
OK, thanks. Closing
